groups:
  - name: application
    rules:

      - alert: PostgreSQLDown
        expr: pg_up == 0
        for: 1m
        labels:
          severity: P1
        annotations:
          summary: "PostgreSQL injoignable sur {{ $labels.instance }}"

      - alert: PostgreSQLConnexionsElevées
        expr: pg_stat_activity_count > 80
        for: 5m
        labels:
          severity: P2
        annotations:
          summary: "Trop de connexions PostgreSQL sur {{ $labels.instance }}"

      - alert: cAdvisorConteneurArrêté
        expr: time() - container_last_seen{name!=""} > 60
        for: 2m
        labels:
          severity: P2
        annotations:
          summary: "Conteneur {{ $labels.name }} arrêté sur {{ $labels.instance }}"
