[monitoring]
nocserv ansible_host=192.168.6.10

[app]
appserv ansible_host=192.168.6.20

[db]
dbserv  ansible_host=192.168.6.30

# Groupes logiques
[all:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_private=~/.ssh/id_rsa
