# --- Versions des outils ---
prometheus_version:         "3.5.3"
alertmanager_version:       "0.33.0"
grafana_version:            "13.0.2"
loki_version:               "3.7.2"
tempo_version:              "2.10.7"
wazuh_version:              "4.14.5"
# -- Agent
node_exporter_version:      "1.11.0"
pg_exporter_version:        "0.19.0"
otel_collector_version:     "0.153.0"
promtail_version:           "3.6.10"
cadvisor_version:           "0.60.1"


# --- Adresses des serveurs (réutilisées dans les templates) ---
monitoring_ip:  "192.168.6.10"
db_ip:          "192.168.6.30"
app_ip:         "192.168.6.20"

# --- Ports globaux ---
prometheus_port:      9090
alertmanager_port:    9093
grafana_port:         3030
loki_port:            3100
tempo_port:           4317
node_exporter_port:   9100
pg_exporter_port:     9187
cadvisor_port:        8080
elasticsearch_port:   9200

# --- Secrets (référencés depuis vault/secrets.yml) ---
grafana_admin_password:   "{{ vault_grafana_admin_password }}"
pg_exporter_password:     "{{ vault_pg_exporter_password }}"
#smtp_password:           "{{ vault_smtp_password }}"
elasticsearch_password:   "{{ vault_elasticsearch_password }}"
