---
- name: restart wazuh-manager
  ansible.builtin.systemd:
    name: wazuh-manager
    state: restarted

- name: restart filebeat
  ansible.builtin.systemd:
    name: filebeat
    state: restarted

