---
- name: Déploiement appserv (serveur application)
  hosts: app
  gather_facts: yes
  vars:
    ansible_become_password: "{{ app_password }}"

  roles:
    - role: common
    - role: infra/docker
    - role: agent/node-exporter
    - role: agent/cadvisor
    - role: agent/promtail
    - role: agent/otel-collector
    - role: agent/wazuh-agent
