---
- name: Déploiement dbserv (serveur base de données)
  hosts: db
  gather_facts: yes
  vars:
    ansible_become_password: "{{ db_password }}"
    update_packages: false

  roles:
    - role: common
    - role: agent/node-exporter
    - role: agent/promtail
    - role: agent/postgresql-exporter
    - role: agent/wazuh-agent
